version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    command: sh -c "cd app; pdm run python manage.py migrate; pdm run gunicorn --bind 0.0.0.0:8000 app.wsgi:application"
    volumes:
      - static_volume:/code/app/static
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles

volumes:
  postgres_data:
  static_volume:
