[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "artemowkin", email = "artyom.groshev2017@gmail.com"},
]
dependencies = [
    "django>=4.1.7",
    "psycopg2-binary>=2.9.5",
    "gunicorn>=20.1.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
